### ISSUE TITLE
Fetch apks from Mobogenie

### ISSUE THREAD

**Issue by mfonville** [opengapps/apkcrawler#11]
Execute a query with the full identifying name of the package, eg:
http://helper.mgccw.com/nclient/sjson/detail/detailInfo.htm?apkId=com.google.android.apps.docs

You'll get some json data back, including a field apkPath and versionCode.

Within versionCode you can find the exact version of the APK.

Attach the value of apkPath to http://download.mgccw.com
This will give you the URL to download the APK.

**Comment by bgiesing** [comment]
I would avoid Mobogenie at **ALL COSTS**

The app re-installs itself (after you remove it purposely), shows millions of popup ads, inserts ads instead of allowing you to go to some webpages, etc. 

Even if the APKs hosted don't have that stuff, I wouldn't take the risk. @mfonville

**Comment by mfonville** [comment]
We won't get any "accidents" because they can't change the APK contents without my verifying mechanism noticing (and refusing to add the APK).
The APKs they have are the same original ones like found on e.g. Aptoide and sometimes they have a really rare version.

**Comment by mfonville** [comment]
I got a beta-version ready.
I believe there is still something wrong about the version number comparing and finding eligable downloads, but I am sure that is something @NicholasBuse can sort out when he will have his betahandling comparison scheme ready.

**Comment by mfonville** [comment]
This crawler is done and stable
