### ISSUE TITLE
Support *.en.uptodown.com

### ISSUE THREAD

**Issue by NicholasBuse** [opengapps/apkcrawler#12]
@mfonville:
I found another source: http://google-drive.en.uptodown.com/android
They have a very simple download URL: http://google-drive.en.uptodown.com/android/download
and here they show all (old) versions: http://google-drive.en.uptodown.com/android/old

**Comment by mfonville** [comment]
Pity is only that the 'real' versioncode is not on the website; so you can only find out the 'real' version of some apps by downloading the APK.

**Comment by mfonville** [comment]
Partially done; only still needs to be able to fetch older versions.
