### ISSUE TITLE
Support apkpure.com

### ISSUE THREAD

**Issue by bgiesing** [opengapps/apkcrawler#18]
https://apkpure.com

NOTE: Some apps are in a new format called XAPK which combines the normal APK and OBB files into a zip file. Don't think any GApps have OBB but good to keep in mind that XAPK files can just be extracted to get the APK

**Comment by mfonville** [comment]
Might http://apk-freedownload.com/ be a copy of them? It looks very alike

**Comment by bgiesing** [comment]
@mfonville I don't know but a lot of these sites are but this is the only one that pulls from GPlay and other trusted sources (APKMirror, etc.), let's you request they check for an update, created a new APK format, has an online sig verification tool, etc.

**Comment by Loverberry** [comment]
http://Loverberry.Tk
Get Lot of educational apps for your kids learning

**Comment by Loverberry** [comment]
http://Loverberry.Tk
Get Lot of educational apps for your kids learning

**Comment by rickymartinss** [comment]
How they are pulling Apps from playstore? i am also working on http://safedl.com/ to make it just like apkpure

**Comment by mfonville** [comment]
I guess they have scripted something or use maybe a custom Playstore client.

**Comment by rickymartinss** [comment]
Do u exactly know what kind of script they are using?

**Comment by mfonville** [comment]
nope. I am not affiliated with them in any way so we don't have any clue.

**Comment by mfonville** [comment]
Done X-D
