### ISSUE TITLE
androidapksfree.com

### ISSUE THREAD

**Issue by mfonville** [opengapps/apkcrawler#32]
Example URL with detailed version history: http://www.androidapksfree.com/version-history/google-photos-apk-version-history/

**Comment by dnyaneshwar123** [comment]
freeapkdownloadz.com

**Comment by mfonville** [comment]
With playstorecrawler complete, not really necessary anymore

**Comment by smartappsapk** [comment]
My Android Apps Blog  **[Smart Apps APK](http://smartappsapk.com)** not getting rank properly is any body tell me how i can check out my posts like http://www.smartappsapk.com/bigo-live-live-broadcasting-apk/
