### ISSUE TITLE
Google Play Store support (and other markets)

### ISSUE THREAD

**Issue by mfonville** [opengapps/apkcrawler#4]
Maybe check out these projects, whether they would be useful:
https://github.com/gpp256/APK-Crawler
https://github.com/mssun/android-apps-crawler

**Comment by mfonville** [comment]
For crawling aptoide stores, these stores have had interesting content in the past:

grungo2407
denis86
benny09
tutu75
msi8
austroid
westcoastandroid
kcprophet
speny
stein-gmg
metin2ventor
migatronic
hot105
pentacore
rodrivergara
eltremendo02
slapchop
mys3
draconius666
letechest
milaupv
ludock96
irishandroid
sandro797
matandroid
hfk217
albrtkmxxo
gyjano

**Comment by mfonville** [comment]
vip-apk

**Comment by mfonville** [comment]
I checked out which google play store api python lib is most up to date, and this specific fork ( https://github.com/RajatGoyal/googleplay-api ) seems to be most updated (since the original repo is no longer maintained).

**Comment by mfonville** [comment]
Done by me.

**Comment by NicholasBuse** [comment]
+1
