### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by bostrot** [opengapps/apkcrawler#57]
Is there any way to provide a bit more detailed tutorial of how to use this apk crawler? I would be glad if there is.

**Comment by NicholasBuse** [comment]
The input to the crawler(s) is the output from a script from the base OpenGApps project: [report_sources.sh](https://github.com/opengapps/opengapps/blob/master/report_sources.sh).

You could create a file manually that contains the information for the APKs that you would like to crawl and feed that into the crawler.  Additionally, there are a couple of scripts that would need to have internal dictionaries update for any new APKs: [uptodowncrawler.py](https://github.com/opengapps/apkcrawler/blob/master/uptodowncrawler.py) and [apkmirrorcrawler.py](https://github.com/opengapps/apkcrawler/blob/master/apkmirrorcrawler.py)

Is that enough (or too much) information?

**Comment by henimerze** [comment]
> The input to the crawler(s) is the output from a script from the base OpenGApps project: [report_sources.sh](https://github.com/opengapps/opengapps/blob/master/report_sources.sh).
> 
> You could create a file manually that contains the information for the APKs that you would like to crawl and feed that into the crawler. Additionally, there are a couple of scripts that would need to have internal dictionaries update for any new APKs: [uptodowncrawler.py](https://github.com/opengapps/apkcrawler/blob/master/uptodowncrawler.py) and [apkmirrorcrawler.py](https://github.com/opengapps/apkcrawler/blob/master/apkmirrorcrawler.py)
> 
> Is that enough (or too much) information?
> 
> Here would be an example for Facebook Messenger and Instagram:
> 
> ```
>                               Application Name| Arch.|SDK|            DPI|                     Version Name|   Version|MiB|Sig.
> -------------------------------------------------------------------------------------------------------------------------------
>                              com.facebook.orca|   arm| 21|        280-640|                     81.0.0.15.78|  34707158|  0|skip
>                              com.facebook.orca|   x86| 21|        280-640|                     81.0.0.15.78|  34707163|  0|skip
>                          com.instagram.android|   arm| 16|        120-160|                            8.5.2|  34875520|  0|skip
>                          com.instagram.android|   arm| 16|        213-240|                            8.5.2|  34875509|  0|skip
>                          com.instagram.android|   arm| 16|            320|                            8.5.2|  34875513|  0|skip
>                          com.instagram.android|   arm| 16|        280-640|                            8.5.2|  34875519|  0|skip
>                          com.instagram.android|   x86| 16|          nodpi|                            8.5.2|  34875525|  0|skip
> ```

Please add this to the readme
