### ISSUE TITLE
Add custom user-agents to crawler curl and python-requests

### ISSUE THREAD

**Issue by archon810** [opengapps/apkcrawler#62]
I was looking at APK Mirror server logs and noticed some hammering. Was about to ban it, but then thought it could be this script. It's using python-requests and curl, searches our site for google apks, downloads, but also uploads.

If it's indeed you guys, to avoid any future accidental blocks and confusion, could you update the code to override the user agents for both curl and python-requests to something custom?

Thanks.

**Comment by NicholasBuse** [comment]
@archon810 

I added the attached user-agent ( {'User-Agent': 'OpenGApps APKMirrorCrawler/1.0'}) as a default for the script. Maarten and I discussed adding an additional configurable user-agent via config file that we could have unique one. (So our user agent for the script would be different than others running this script). Does that have any value to you?

Also, I have a PR (https://github.com/opengapps/opengapps/pull/425) to add a user-agent to our upload scripts (curl would use: -A "OpenGAppsUploader")

**Comment by archon810** [comment]
Thanks for the quick commits @NicholasBuse!

Re: custom user agents, I don't have a strong opinion, because unless it's a forced feature that ensures the UA is unique, people will just either use the sample one or just leave it blank and default to yours. As long as I can tell this scraper from hammer bots, we're good.
