### ISSUE TITLE
Missing files!

### ISSUE THREAD

**Issue by xyphanajay** [opengapps/apkcrawler#70]
Scripts are missing from the repo!
add_sourceapp.sh and  report_sources.sh 

These files are used in README and instructed to use them but are missing in repo.

**Comment by NicholasBuse** [comment]
The files you are referencing are part of the [opengapps/opengapps](https://github.com/opengapps/opengapps) repo.

For a better descriptions see the closed issue: https://github.com/opengapps/apkcrawler/issues/57#issuecomment-236244190

**Comment by xyphanajay** [comment]
Thank you

**Comment by MrRobotAptoide** [comment]
Spanks

**Comment by 1268** [comment]
https://github.com/opengapps/apkcrawler/issues/77
