### ISSUE TITLE
fix apkmirror case where number of versioncodes exceed display

### ISSUE THREAD

**Issue by NicholasBuse** [opengapps/apkcrawler#9]
http://www.apkmirror.com/apk/google-inc/google-play-services/ sorts by versioncode (not upload date) and only shows the highest 15 apks.

If all 15 have the same same version, then additionally crawl: http://www.apkmirror.com/uploads/?app=google-play-services

The 2nd page sorts by upload date but shows 30 apks

**Comment by mfonville** [comment]
So if I understand the code correctly, it does now not 'additionally' crawl but just by default crawls the other page?

**Comment by NicholasBuse** [comment]
yeah, sorry.  The change to crawl the 2nd page gives us access to the latest 30 uploads. Currently GMSCore only has 23 (including leanback).

**Comment by NicholasBuse** [comment]
You must be brushing up on your python :smile:

**Comment by mfonville** [comment]
Nah, I am still a python n00b and can't really do anything with it, but I do can read the logic of your code ;-)

**Comment by NicholasBuse** [comment]
eeew...the full crawl time (python apkcrawler.py) went from <4min to ~10min with this change

**Comment by mfonville** [comment]
Maybe you can use some threading for the HTTP requests?

**Comment by NicholasBuse** [comment]
HTTP time should not have changed much, it is most likely the speed of parsing the HTML with BeautifulSoup (python module).  The page size on gmscore's case is ~2KB bigger with more elements to parse.  Maybe I'd be better off with straight string parsing instead of parsing module...

**Comment by mfonville** [comment]
Then threading the requests in general, in such a way that the parsing is also threaded?

**Comment by NicholasBuse** [comment]
I'll slowly figure it out...the server response time is ~175ms for original page, and ~1400ms for the new. (1.225s * 50 apps = ~ 1min. more). The threading I added got the full time ~2 min (so better than before this update...)

**Comment by mfonville** [comment]
awesome :-)
